"""Turns a portrait into constellation data: star positions (0..1) with brightness, and the lines joining neighbours.
Usage: python3 tools/make_constellation.py <portrait.png> js/constellation.js [preview.png]"""
import sys, json, math
import numpy as np
from PIL import Image, ImageFilter

src, out = sys.argv[1], sys.argv[2]
prev = sys.argv[3] if len(sys.argv) > 3 else None
S = 320                                              # working size
im = Image.open(src).convert('RGBA').resize((S, S), Image.LANCZOS)
rgb = np.asarray(im.convert('RGB')).astype(float)
alpha = np.asarray(im)[:, :, 3].astype(float) / 255
lum = rgb @ np.array([0.299, 0.587, 0.114]) / 255

# subject mask: not (almost) white background, softened
bg = (rgb.min(axis=2) > 232) | (alpha < 0.2)
mask = (~bg).astype(float)
mask_img = Image.fromarray((mask * 255).astype('uint8')).filter(ImageFilter.MedianFilter(5)).filter(ImageFilter.GaussianBlur(1.2))
mask = np.asarray(mask_img).astype(float) / 255

blur = np.asarray(Image.fromarray((lum * 255).astype('uint8')).filter(ImageFilter.GaussianBlur(1.1))).astype(float) / 255
gy, gx = np.gradient(blur)
edge = np.hypot(gx, gy)
edge = edge / (np.percentile(edge[mask > 0.5], 99) + 1e-6)
edge = np.clip(edge, 0, 1)

# local darkness: hair, brows, eyes, mouth, shadows are darker than the face around them
local = np.asarray(Image.fromarray((lum * 255).astype('uint8')).filter(ImageFilter.GaussianBlur(7))).astype(float) / 255
dark = np.clip((local - blur) * 4.5, 0, 1)
# face area boost: eyes, brows, nose and mouth live in the middle of the picture
fy, fx = np.mgrid[0:S, 0:S]
face = np.exp(-(((fx - 0.52 * S) / (0.26 * S)) ** 2 + ((fy - 0.52 * S) / (0.26 * S)) ** 2))

# silhouette ring (outline of head, hair and shoulders)
er = np.asarray(Image.fromarray((mask * 255).astype('uint8')).filter(ImageFilter.MinFilter(5))).astype(float) / 255
ring = np.clip(mask - er, 0, 1)

feat = ((0.6 + 0.9 * face) * edge + (0.6 + 0.9 * face) * dark) * (er > 0.5)       # interior only: eyes, brows, nose, mouth, hair texture
feat = np.asarray(Image.fromarray((np.clip(feat, 0, 1) * 255).astype('uint8')).filter(ImageFilter.GaussianBlur(1.0))).astype(float) / 255
rng = np.random.default_rng(7)
yy, xx = np.mgrid[0:S, 0:S]

def pick(score_map, n, minr, floor, jitter=0.03):
    sm = score_map.copy()
    got = []
    for _ in range(n):
        i = np.argmax(sm + rng.random(sm.shape) * jitter)
        y, x = divmod(int(i), S)
        if sm[y, x] < floor:
            break
        got.append((x, y, float(min(1.0, score_map[y, x] * 1.4))))
        sm[(xx - x) ** 2 + (yy - y) ** 2 < minr * minr] = 0
    return got

# star tiers, big to tiny. Each tier is sampled with its own spacing, so the portrait has bright anchor stars,
# a mid layer that carries the features, and fine dust that shades hair, brows, eyes and shadows.
shade = np.clip((1 - lum) * 1.25, 0, 1) * (mask > 0.4)                    # dark areas (hair, brows, eyes, mouth, shadow)
dust_map = np.clip(0.55 * shade + 0.5 * edge + 0.25 * face * (mask > 0.4) + 0.4 * ring, 0, 1) * (mask > 0.3)

big    = pick(np.maximum(ring, feat * 1.2), 95, 12.0, 0.18)
mid    = pick(feat + 0.6 * ring, 300, 6.8, 0.09)
small  = pick(dust_map, 800, 3.7, 0.07)
tiny = []   # sampled below, after the other tiers, so it fills the gaps (cheeks, forehead, nose, chin)

def occupied(group, r):
    m = np.zeros((S, S), bool)
    for x, y, _ in group:
        m[(xx - x) ** 2 + (yy - y) ** 2 < r * r] = True
    return m

# keep each finer tier from piling onto the coarser ones
blocked = occupied(big, 5.0)
mid = [p for p in mid if not blocked[p[1], p[0]]]
blocked |= occupied(mid, 3.0)
small = [p for p in small if not blocked[p[1], p[0]]]
blocked |= occupied(small, 1.9)
blocked |= occupied(small, 3.2)
flat = ((er > 0.5) * (yy < 0.74 * S)).astype(float) * (0.5 + 0.25 * (1 - lum))
flat[blocked] = 0
tiny = pick(flat, 420, 6.2, 0.05, jitter=0.4)

pts = [(x, y, m, 3) for x, y, m in big] + [(x, y, m, 2) for x, y, m in mid] + [(x, y, m, 1) for x, y, m in small] + [(x, y, m, 0) for x, y, m in tiny]

# lines join the big and mid stars to their nearest neighbours; small and tiny stars are just scatter
P = np.array([(x, y) for x, y, _, _ in pts])
cls = np.array([c for _, _, _, c in pts])
edges = set()
linkable = [i for i in range(len(pts)) if cls[i] >= 2]
for a in linkable:
    d = np.hypot(*(P - P[a]).T)
    d[cls < 2] = 1e9
    order = np.argsort(d)[1:4]
    for k, b in enumerate(order):
        if d[b] <= 20 and (k < 2 or d[b] <= 12):
            edges.add((min(a, int(b)), max(a, int(b))))

data = {
    'stars': [[round(x / S, 4), round(y / S, 4), round(0.3 + 0.7 * min(1.0, m), 2), c] for x, y, m, c in pts],
    'lines': sorted([list(e) for e in edges]),
}
open(out, 'w').write('/* Generated by tools/make_constellation.py from the portrait: stars (x, y, brightness, size class 0-3) and the lines joining them. */\nwindow.CONSTELLATION = ' + json.dumps(data, separators=(',', ':')) + ';\n')
print(len(big), 'big', len(mid), 'mid', len(small), 'small', len(tiny), 'tiny', len(edges), 'lines')

if prev:
    from PIL import ImageDraw
    P2 = 900
    pv = Image.new('RGB', (P2, P2), (10, 10, 16))
    dr = ImageDraw.Draw(pv)
    for a, b in edges:
        dr.line([P[a][0] / S * P2, P[a][1] / S * P2, P[b][0] / S * P2, P[b][1] / S * P2], fill=(110, 100, 55), width=1)
    rad = {3: 4.4, 2: 2.8, 1: 1.7, 0: 1.0}
    for x, y, m, c in pts:
        r = rad[c]
        cx, cy = x / S * P2, y / S * P2
        dr.ellipse([cx - r, cy - r, cx + r, cy + r], fill=(255, 238, 130))
    pv.save(prev)
